version: "3.8"

services:
  backend:
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app-backend:/app
      - backend_uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./app-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app-web:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000/api
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend_uploads:
